---
- name: reconfigure lxd
  command: dpkg-reconfigure --frontend noninteractive lxd

- name: restart lxd
  service: name=lxd-bridge state=stopped
  notify: restart lxdb

- name: restart lxdb
  service: name=lxd state=restarted