---
- name: remove names loopback
  lineinfile: dest=/etc/hosts regexp="^(127.0.1.1.*)" line="#\1" backrefs=1

- name: interhost entries
  lineinfile: dest=/etc/hosts line="{{ hostvars[item]['ansible_' + management_iface]['ipv4']['address'] }}    {{  hostvars[item]['ansible_hostname'] }}" state="present"
  with_items: play_hosts