---
- name: mariadb config
  template: src=mysql_openstack.cnf.j2 dest=/etc/mysql/conf.d/openstack.cnf
  tags: [ mysql, mariadb, galera, configuration, install ]

# if kludge in template due to lack of "do" statement

