---
- name: "Debug applications"
  hosts: debugs
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: "install items"
      apt: name={{ item }} state=present
      with_items:
        - debconf-utils


