---
- name: "Debug applications"
  hosts: debugs
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - command: pcs
        {% set space = joiner(" ") %}
        {% for item in play_hosts -%}
        {{ space() }}{{ hostvars[item].ansible_hostname }}
        {%- endfor %}

  tags:
    - debug
    



    