---
- name: "Initialise target servers"
  hosts: servers
  become: true
  become_user: root
  become_method: sudo
  gather_facts: no
  
  pre_tasks:

    - name: "install python-apt"
      become_user: root
      raw: "apt install python python-apt -y"
      tags:
        - package

  tasks:
    
    - name: "system user authorized_keys"
      authorized_key: user=system key="{{ item }}"
      with_file:
        - ../ansible_rsa.pub
      tags:
        - security
        
    - name: "sudo group needs no password"
      lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
      tags:
        - security

  tags:
    - init
    
