---
# - name: "Tasks for Openstack servers"
#   hosts: servers
#   roles:
#     - openstack

# - name: "Tasks for Galera cluster"
#   hosts: galera_cluster
#   roles:
#     - galera
#   tags: galera

# - name: "Start Galera cluster"
#   hosts: galera_cluster
#   serial: 1
#   roles:
#     - galera_bootstrap
#   tags: galera

- name: "Tasks for RabbitMQ"
  hosts: rabbitmq_cluster
  roles:
    - rabbitmq
  tags: rabbitmq

- name: "Start RabbitMQ cluster"
  hosts: rabbitmq_cluster
  serial: 1
  roles:
    - rabbitmq_bootstrap
  tags: rabbitmq
