---
# - name: "Tasks for Openstack servers"
#   hosts: servers
#   roles:
#     - openstack
#   tags: openstack

# - name: "Tasks for Galera cluster"
#   hosts: galera_cluster
#   roles:
#     - galera
#   tags: [ openstack, galera ]

# - name: "Start Galera cluster"
#   hosts: galera_cluster
#   serial: 1
#   roles:
#     - galera_bootstrap
#   tags: [ openstack, galera ]

- name: "Tasks for RabbitMQ"
  hosts: rabbitmq_cluster
  roles:
    - rabbitmq
  tags: [ openstack, rabbitmq ]
