---
- name: "Tasks for all Openstack servers"
  hosts: servers
  roles:
    - openstack
  tags: [ install ]

- name: "Tasks for Galera cluster"
  hosts: galera_cluster
  roles:
    - galera
  tags: [ galera, install ]

- name: "Start Galera cluster"
  hosts: galera_cluster
  serial: 1
  roles:
    - galera_bootstrap
  tags: [ galera, bootstrap ]

- name: "Tasks for RabbitMQ"
  hosts: rabbitmq_cluster
  roles:
    - rabbitmq
  tags: [ rabbitmq, install ]

- name: "Start RabbitMQ cluster"
  hosts: rabbitmq_cluster
  serial: 1
  roles:
    - rabbitmq_bootstrap
  tags: [ rabbitmq, bootstrap ]
